"""
lib/team_selector.py
Team Selection Engine — fills the optimized seed bracket with actual teams.

The 64-team field uses placeholder ratings.  Swap MOCK_TEAMS for a
live data source to connect real season stats.

Pipeline
--------
  1. Score each team (rating + seed quality + champion profile)
  2. For each potential upset, compute:
       win_probability  — historical rate this underdog seed beats this favorite seed
       upset_quality    — win_probability × (underdog_score / favorite_score)
  3. Select upsets that clear both per-mode thresholds:
       UPSET_MIN_WIN_PROB     — minimum historical win rate (hard gate)
       UPSET_MIN_DESIRABILITY — minimum composite quality score (soft gate)
     No fixed count is applied; the number of upsets is determined by how many
     matchups clear the thresholds in each round.
  4. Apply the Sweet 16 composition constraint (enforces DD seed presence)
  5. Simulate every round, attach upset_quality to each upset game result
  6. Report structure compliance — upset counts are informational only;
     the only enforced constraint is Sweet 16 double-digit seed composition
"""

import json
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent

# Team ratings integration — optional; falls back to seed-based logic when absent.
try:
    from lib.team_ratings import (
        load_team_ratings        as _load_team_ratings,
        load_historical_ratings  as _load_historical_ratings,
        get_team_rating          as _get_team_rating,
        get_team_rating_by_id    as _get_team_rating_by_id,
        predict_win_probability  as _predict_win_probability,
        OUTPUT_CSV               as _CURRENT_RATINGS_CSV,
        HIST_CSV                 as _HIST_RATINGS_CSV,
    )
    _HAS_TEAM_RATINGS = True
except ImportError:
    _HAS_TEAM_RATINGS = False

# Matches "T{integer}" team names produced by the backtest engine.
_TEAM_ID_RE = re.compile(r"^T(\d+)$")
OPT_FILE     = PROJECT_ROOT / "data" / "processed" / "optimal_bracket_structure.json"
PROBS_FILE   = PROJECT_ROOT / "data" / "processed" / "seed_probabilities.json"
OUTPUT_FILE  = PROJECT_ROOT / "data" / "processed" / "generated_bracket.json"

# ── Bracket layout constants ──────────────────────────────────────────────────

REGIONS = ["East", "West", "South", "Midwest"]

# Standard first-round seed matchups within each region.
# Each tuple is (lo_seed, hi_seed): lo_seed is the favorite, hi_seed the underdog.
R64_MATCHUPS = [(1,16), (8,9), (5,12), (4,13), (6,11), (3,14), (7,10), (2,15)]

# Round-of-32: pair R64 game-slot winners (0,1), (2,3), (4,5), (6,7)
R32_PAIRS = [(0,1), (2,3), (4,5), (6,7)]

# Sweet 16: pair R32 game-slot winners (0,1), (2,3)
S16_PAIRS = [(0,1), (2,3)]

# Final Four: East vs West, South vs Midwest (indices into REGIONS list)
FF_REGION_PAIRS = [(0,1), (2,3)]   # (East,West), (South,Midwest)

# ── Mock team field (replace with live data for a real season) ────────────────
# Ratings are on a 20–96 scale calibrated to seed tiers with intra-tier variance.
# One team per seed per region = 64 teams total.

MOCK_TEAMS: dict[str, dict[int, dict]] = {
    # Names match the sample dataset generated by build_team_ratings.py so that
    # simulate_bracket(season=2025) can attach real team_rating / champion_profile_score.
    "East": {
        1:  {"name": "Riverside",     "rating": 94.0},
        2:  {"name": "Lakewood",      "rating": 87.5},
        3:  {"name": "Millfield",     "rating": 81.5},
        4:  {"name": "Creekside",     "rating": 76.0},
        5:  {"name": "Westmont",      "rating": 71.5},
        6:  {"name": "Hillbrook",     "rating": 66.5},
        7:  {"name": "Oakdale",       "rating": 62.0},
        8:  {"name": "Fernwood",      "rating": 57.5},
        9:  {"name": "Pinehurst",     "rating": 52.5},
        10: {"name": "Sycamore",      "rating": 48.5},
        11: {"name": "Clearwater",    "rating": 44.5},
        12: {"name": "Elmhurst",      "rating": 41.0},
        13: {"name": "Ridgemont",     "rating": 37.5},
        14: {"name": "Cedarville",    "rating": 33.5},
        15: {"name": "Maplewood",     "rating": 29.0},
        16: {"name": "Stonegate",     "rating": 23.5},
    },
    "West": {
        1:  {"name": "Summit",        "rating": 93.0},
        2:  {"name": "Harborview",    "rating": 86.0},
        3:  {"name": "Cliffside",     "rating": 82.5},
        4:  {"name": "Bayshore",      "rating": 77.5},
        5:  {"name": "Cascadia",      "rating": 72.0},
        6:  {"name": "Redwood",       "rating": 67.5},
        7:  {"name": "Lakeview",      "rating": 63.0},
        8:  {"name": "Northport",     "rating": 58.0},
        9:  {"name": "Eastbrook",     "rating": 53.0},
        10: {"name": "Pineridge",     "rating": 49.5},
        11: {"name": "Holloway",      "rating": 45.5},
        12: {"name": "Belmont",       "rating": 40.5},
        13: {"name": "Fairfield",     "rating": 37.0},
        14: {"name": "Greendale",     "rating": 33.0},
        15: {"name": "Ashford",       "rating": 29.5},
        16: {"name": "Brookhaven",    "rating": 23.0},
    },
    "South": {
        1:  {"name": "Midland",       "rating": 92.0},
        2:  {"name": "Southport",     "rating": 88.0},
        3:  {"name": "Crestview",     "rating": 80.5},
        4:  {"name": "Ironwood",      "rating": 78.0},
        5:  {"name": "Sunridge",      "rating": 72.5},
        6:  {"name": "Palmview",      "rating": 68.0},
        7:  {"name": "Glendale",      "rating": 61.5},
        8:  {"name": "Westfield",     "rating": 56.5},
        9:  {"name": "Lakeside",      "rating": 53.5},
        10: {"name": "Thornwood",     "rating": 50.0},
        11: {"name": "Rosewood",      "rating": 46.0},
        12: {"name": "Foxhill",       "rating": 42.5},
        13: {"name": "Springdale",    "rating": 36.5},
        14: {"name": "Deerfield",     "rating": 32.5},
        15: {"name": "Weston",        "rating": 28.0},
        16: {"name": "Riverdale",     "rating": 22.5},
    },
    "Midwest": {
        1:  {"name": "Northland",     "rating": 95.5},
        2:  {"name": "Hillcrest",     "rating": 85.0},
        3:  {"name": "Eastgate",      "rating": 83.0},
        4:  {"name": "Bluewater",     "rating": 75.5},
        5:  {"name": "Prairieton",    "rating": 71.0},
        6:  {"name": "Cannonball",    "rating": 66.0},
        7:  {"name": "Redstone",      "rating": 62.5},
        8:  {"name": "Wheatfield",    "rating": 57.0},
        9:  {"name": "Cornbury",      "rating": 51.5},
        10: {"name": "Irondale",      "rating": 47.5},
        11: {"name": "Silverstone",   "rating": 43.0},
        12: {"name": "Copperhill",    "rating": 39.5},
        13: {"name": "Dusty Mesa",    "rating": 36.0},
        14: {"name": "Flatrock",      "rating": 32.0},
        15: {"name": "Timberline",    "rating": 28.5},
        16: {"name": "Plainview",     "rating": 22.0},
    },
}


# ════════════════════════════════════════════════════════════════════════════
# Team scoring
# ════════════════════════════════════════════════════════════════════════════

def score_team(team: dict, adv_rates: dict) -> float:
    """
    Composite team quality score in [0, 1].

    Components
    ----------
    rating_score  (60 %) — normalised placeholder rating (20-96 scale)
    seed_quality  (25 %) — linear seed advantage: seed 1 = 1.0, seed 16 = 0.0
    champ_profile (15 %) — historical probability that a team of this seed
                           wins the championship (from advancement_rates)

    The champion-profile term rewards seeds with a realistic track record
    of going deep, slightly boosting teams that are both high-rated AND
    from a historically strong seed tier.
    """
    seed = team["seed"]

    # Rating component: use real team_rating [0,1] when available; else normalize
    # the placeholder 20–96 scale rating.
    if "team_rating" in team:
        rating_score = float(team["team_rating"])
    else:
        rating_score = (team["rating"] - 20) / 76.0

    seed_quality = (17 - seed) / 16.0             # seed 1 → 1.0, seed 16 → 0.0625

    # Champion profile: use real champion_profile_score [0,1] when available;
    # else derive from historical advancement rates.
    if "champion_profile_score" in team:
        champ_profile = float(team["champion_profile_score"])
    else:
        champ_rate    = adv_rates.get(str(seed), {}).get("champion", 0.0)
        max_rate      = adv_rates.get("1", {}).get("champion", 0.148)
        champ_profile = min(1.0, champ_rate / max_rate) if max_rate > 0 else 0.0

    return round(0.60 * rating_score + 0.25 * seed_quality + 0.15 * champ_profile, 4)


# ════════════════════════════════════════════════════════════════════════════
# Upset-selection thresholds
# ════════════════════════════════════════════════════════════════════════════

# Eligible underdog seed range, by round.
# Early rounds (R64–S16): only double-digit seeds (10–13) are eligible underdogs.
#   Seeds 14–16 win too rarely to pick reliably; seeds 8–9 are excluded entirely.
# Late rounds (E8+): expand to 2–13 so that 2/3/4-seeds can beat 1-seeds.
#   These matchups are historically plausible (2v1 ≈44%, 3v1 ≈31%) and produce
#   realistic Final Four variety.
ROUND_SEED_RANGE: dict[str, tuple[int, int]] = {
    "Round of 64":  (10, 13),
    "Round of 32":  (10, 13),
    "Sweet 16":     (10, 13),
    "Elite 8":      (2,  13),
    "Final Four":   (2,  13),
    "Championship": (2,  13),
}

# Minimum historical win probability for the underdog seed in this matchup type.
# Acts as a hard gate; calibrated from 1985–2016 data (seed_probabilities.json):
#   R64 win rates: 10v7≈39%, 11v6≈36%, 12v5≈36%, 13v4≈20%
# Conservative admits only the top tier (≥28%); balanced and upset_heavy
# also admit the 13v4 tier (≥20%).
UPSET_MIN_WIN_PROB: dict[str, float] = {
    "conservative": 0.28,
    "balanced":     0.22,
    "upset_heavy":  0.22,
}

# Minimum upset desirability score: win_probability × (underdog_score / favorite_score).
# Acts as a quality gate: excludes matchups where the underdog is too weak
# relative to the favorite, even if the seed matchup has historical precedent.
UPSET_MIN_DESIRABILITY: dict[str, float] = {
    "conservative": 0.12,
    "balanced":     0.07,
    "upset_heavy":  0.04,
}

# Per-round relaxation of UPSET_MIN_WIN_PROB[mode] (negative = more permissive).
# Later rounds feature stronger surviving teams; the early-round threshold is
# too strict for matchups like 2v1 or 3v1, which are historically common.
ROUND_PROB_DELTA: dict[str, float] = {
    "Sweet 16":    -0.03,
    "Elite 8":     -0.05,
    "Final Four":  -0.05,
    "Championship": -0.05,
}

# Hard cap on total upset picks per round, by mode.
# Candidates are ranked by desirability; only the top N are selected.
# E8/FF/Championship caps are intentionally loose — the gate thresholds and
# FF balance bias are the primary controls in late rounds.
UPSET_MAX_BY_ROUND: dict[str, dict[str, int]] = {
    "Round of 64":  {"conservative": 5,  "balanced": 7,  "upset_heavy": 9},
    "Round of 32":  {"conservative": 2,  "balanced": 3,  "upset_heavy": 4},
    "Sweet 16":     {"conservative": 1,  "balanced": 1,  "upset_heavy": 2},
    "Elite 8":      {"conservative": 1,  "balanced": 2,  "upset_heavy": 2},
    "Final Four":   {"conservative": 1,  "balanced": 1,  "upset_heavy": 2},
    "Championship": {"conservative": 1,  "balanced": 1,  "upset_heavy": 1},
}

# Per-region caps for Round of 64 only.
# Prevents all three mid-tier upsets (10v7, 11v6, 12v5) from firing in the
# same region, which would cascade into DD-vs-DD paths in later rounds.
UPSET_MAX_PER_REGION_R64      = 2   # total upsets per region
UPSET_MAX_MID_TIER_PER_REGION = 2   # of the three types 10v7 / 11v6 / 12v5

# The three mid-tier R64 matchup types that cause cascade problems when all fire
_MID_TIER_MATCHUPS: frozenset[tuple[int, int]] = frozenset({(5, 12), (6, 11), (7, 10)})

# Global per-seed-line caps for Round of 64.
# Prevents one seed line from monopolising all upsets (e.g. all four 10-seeds
# winning while no 12-seeds advance, which is historically rare and
# bracket-quality-degrading).  The greedy selector fills the best N picks
# across the whole field per seed number.
#
# Calibrated from 1985–2024 data:
#   10v7: average ~1.5 wins/year   → cap 2 (allow the best two)
#   11v6: average ~1.3 wins/year   → cap 2
#   12v5: average ~1.5 wins/year   → cap 2 (ensure bracket has 12-seed variety)
#   13v4: average ~0.4 wins/year   → cap 1
R64_GLOBAL_SEED_CAPS: dict[str, dict[int, int]] = {
    "conservative": {10: 1, 11: 1, 12: 1, 13: 0},
    "balanced":     {10: 2, 11: 2, 12: 2, 13: 1},
    "upset_heavy":  {10: 3, 11: 3, 12: 2, 13: 1},
}

# Soft Final Four balance bias — applied to E8 upset candidates' desirability
# scores (for ranking and gate purposes) based on how many 1-seeds are projected
# to reach the FF by default.  Encourages ~2 1-seeds; discourages 0 or 4.
# Does NOT block any outcome — only shifts the probability of selection.
_FF_BALANCE_MULTIPLIER: dict[int, float] = {
    4: 1.50,   # all 4 games have 1-seed favorites → strongly boost upsets
    3: 1.20,   # 3 of 4 → mild boost
    2: 1.00,   # 2 of 4 → neutral (ideal target state)
    1: 0.70,   # 1 of 4 → mild penalty on further upsets
    0: 0.40,   # 0 of 4 → strong penalty
}

# Soft gate for the second Elite 8 upset in balanced mode only.
# After the first E8 upset is selected, any subsequent candidate must have
# biased desirability (post-FF-balance-multiplier) above this value to be
# selected.  This discourages the second upset without blocking it outright:
# strong matchups (high biased desirability) still pass; weak ones are skipped.
#
# Calibrated from 1990–2016 pre-tournament win rates:
#   biased desirability for 2v1 E8 ranges 0.476–0.597 (mean ≈ 0.530)
#   gate=0.540 → second upset passes in ~9/22 measured years → ~65% 1-seeds
_BALANCED_E8_SECOND_GATE: float = 0.540

# Rounds where champion profile is blended into win probability for upset scoring.
_LATE_ROUNDS: frozenset[str] = frozenset({"Elite 8", "Final Four", "Championship"})

# AP Week 6 tie-breaker: small bonus applied to the late_term of underdogs who
# were AP top-12 at Week 6, but ONLY in Final Four and Championship decisions.
# Not used in Elite 8 or earlier rounds — AP Week 6 is too early-season to be
# reliable; reserve it as a minor signal only when teams reach the final stage.
_AP_FF_ROUNDS:  frozenset[str] = frozenset({"Final Four", "Championship"})
_AP_FF_BONUS:   float          = 0.03   # ≤ 5% influence on late_term (≤0.3% on final desirability)

# Seed-based public pick percentage for late-round advancement.
# Approximate calibration from ESPN Tournament Challenge distributions:
# 1-seeds receive ~55–60% of FF picks; 2-seeds ~20%; drops sharply after.
# Used when a team has no real public_pick_pct attached (backtest / no data).
_SEED_PUBLIC_PICK_LATE: dict[int, float] = {
    1: 0.58, 2: 0.20, 3: 0.10, 4: 0.05,
    5: 0.02, 6: 0.01, 7: 0.01, 8: 0.005,
    9: 0.004, 10: 0.003, 11: 0.003, 12: 0.002,
    13: 0.001, 14: 0.001, 15: 0.000, 16: 0.000,
}

# Win probability gap above which a close matchup gets a value_score boost.
_CLOSE_MATCHUP_WP_BAND: float = 0.12   # |wp − 0.5| < 0.12 → "close"
_CLOSE_MATCHUP_VALUE_WEIGHT: float = 0.05

# Elite-seed protection: when the favorite has seed ≤ this value AND
# the team_rating gap exceeds the threshold, multiply desirability down.
#
# Rationale: a 1- or 2-seed with a large efficiency advantage should not be
# routed out early by the historical seed-vs-seed upset rates alone.  The
# team_rating gap threshold of 0.16 corresponds to roughly 10 AdjEM points
# in a typical 64-team field (team_rating is min-max normalised 0.10–0.95
# over ~52 EM points, so 0.16 ≈ 10 EM).  Below the threshold the matchup
# is close enough that normal upset logic applies.
_ELITE_PROTECT_MAX_SEED:    int   = 2     # seed ≤ 2 gets protection
_ELITE_PROTECT_RATING_GAP:  float = 0.16  # team_rating gap ≈ 10 AdjEM pts
_ELITE_PROTECT_MULTIPLIER:  float = 0.50  # halve desirability when gap exceeded



# ════════════════════════════════════════════════════════════════════════════
# Game-selection helpers
# ════════════════════════════════════════════════════════════════════════════

def _is_8v9(seed_a: int, seed_b: int) -> bool:
    """8-vs-9 matchups are treated as pick'em; no upset is counted."""
    return {seed_a, seed_b} == {8, 9}


def _upset_rate(fav_seed: int, und_seed: int, win_rates: dict) -> float:
    """
    Historical win rate of the underdog (und_seed) over the favorite (fav_seed).
    Key format matches matchup_win_rates: "{higher}_vs_{lower}".
    Returns 0.0 when there is no historical precedent.
    """
    key = f"{und_seed}_vs_{fav_seed}"
    return win_rates.get(key, 0.0)


def _get_public_pick_pct(team: dict, opponent: dict) -> float:
    """
    Estimate the fraction of public brackets that pick 'team' to win this game.

    Uses team["public_pick_pct"] if set (real-data override), otherwise derives
    a game-specific estimate from the seed-based prior by normalizing each team's
    seed weight to the specific matchup:

        pct = seed_weight(team) / (seed_weight(team) + seed_weight(opponent))

    Returns a value in (0, 1).
    """
    if "public_pick_pct" in team and team["public_pick_pct"] is not None:
        return float(team["public_pick_pct"])
    raw_t = _SEED_PUBLIC_PICK_LATE.get(team["seed"], 0.001)
    raw_o = _SEED_PUBLIC_PICK_LATE.get(opponent["seed"], 0.001)
    total = raw_t + raw_o
    return raw_t / total if total > 0 else 0.5


def _upset_desirability(
    team_a:     dict,
    team_b:     dict,
    win_rates:  dict,
    round_name: str = "",
) -> float:
    """
    How warranted is an upset pick for this matchup?

    When team ratings are available (team_rating field in both team dicts):

      upset_score =
        0.60 × underdog_win_prob      (from predict_win_probability)
      + 0.20 × historical_upset_rate  (structural desirability)
      + 0.20 × score_ratio            (underdog_score / favorite_score)

    In late rounds (Elite 8, Final Four, Championship), the win_prob term is
    replaced by a champion-profile blend:

      value_score = underdog_win_prob − public_pick_pct(underdog)

      Elite 8:      late_term = 0.60 × wp + 0.20 × champion_profile_score + 0.10 × profile_score + 0.10 × value_score
      Final Four:   late_term = 0.50 × wp + 0.20 × champion_profile_score + 0.15 × profile_score + 0.15 × value_score
      Championship: late_term = 0.50 × wp + 0.20 × champion_profile_score + 0.20 × profile_score + 0.10 × value_score
      upset_score = 0.60 × late_term + 0.20 × hist_rate + 0.20 × score_ratio

    Close matchup boost (all rounds, when |wp − 0.5| < 0.12):
      upset_score += _CLOSE_MATCHUP_VALUE_WEIGHT × value_score

    Fallback (no team_rating available): legacy formula:
      desirability = historical_upset_rate × score_ratio

    Returns 0.0 for 8v9 games or matchups with no historical upset record.
    """
    if _is_8v9(team_a["seed"], team_b["seed"]):
        return 0.0
    if team_a["seed"] < team_b["seed"]:
        fav, und = team_a, team_b
    elif team_b["seed"] < team_a["seed"]:
        fav, und = team_b, team_a
    else:
        return 0.0

    hist_rate = _upset_rate(fav["seed"], und["seed"], win_rates)
    if hist_rate == 0.0:
        return 0.0

    score_ratio = und["score"] / fav["score"] if fav["score"] > 0 else 0.0

    # ── Rating-based path ─────────────────────────────────────────────────
    if _HAS_TEAM_RATINGS and "team_rating" in und and "team_rating" in fav:
        wp = _predict_win_probability(und, fav)["team_a"]

        # value_score: underdog modeled win prob vs. public expectation
        und_pub     = _get_public_pick_pct(und, fav)
        value_score = wp - und_pub

        if round_name in _LATE_ROUNDS and "champion_profile_score" in und:
            ps  = float(und.get("profile_score", 0.5))
            cps = float(und["champion_profile_score"])
            if round_name == "Championship":
                late_term = 0.50 * wp + 0.20 * cps + 0.20 * ps + 0.10 * value_score
            elif round_name == "Final Four":
                late_term = 0.50 * wp + 0.20 * cps + 0.15 * ps + 0.15 * value_score
            else:  # Elite 8
                late_term = 0.60 * wp + 0.20 * cps + 0.10 * ps + 0.10 * value_score

            # AP tie-breaker: Final Four and Championship only.
            # Adds a small bonus when the underdog was AP top-12 at Week 6.
            if round_name in _AP_FF_ROUNDS and und.get("ap_top12_flag", 0) == 1:
                late_term_pre = late_term
                late_term = late_term + _AP_FF_BONUS
                print(
                    f"  [AP] {und['name']} (seed {und['seed']}) AP top-12 bonus "
                    f"+{_AP_FF_BONUS:.3f} applied in {round_name}  "
                    f"(late_term {late_term_pre:.4f} → {late_term:.4f})"
                )

            score = round(0.60 * late_term + 0.20 * hist_rate + 0.20 * score_ratio, 5)

        else:
            score = round(0.60 * wp + 0.20 * hist_rate + 0.20 * score_ratio, 5)

            # Close matchup value boost (non-late or no profile data)
            if abs(wp - 0.5) < _CLOSE_MATCHUP_WP_BAND:
                score = round(score + _CLOSE_MATCHUP_VALUE_WEIGHT * value_score, 5)

    else:
        # ── Seed-based fallback ───────────────────────────────────────────
        score = round(hist_rate * score_ratio, 5)

    # ── Elite-seed protection ─────────────────────────────────────────────
    # When the favorite is a 1- or 2-seed and the team_rating gap is large
    # (≈ > 10 AdjEM pts), halve the desirability score.  This makes it very
    # unlikely the upset clears the min_desirability gate, preventing elite
    # teams from being routed out by historically plausible but tactically
    # implausible matchups (e.g. a #10 seed beating a dominant #2 seed).
    # The check requires team_rating to be present on both teams; the fallback
    # path (no ratings) is unaffected.
    if (fav["seed"] <= _ELITE_PROTECT_MAX_SEED
            and "team_rating" in fav and "team_rating" in und
            and (fav["team_rating"] - und["team_rating"]) > _ELITE_PROTECT_RATING_GAP):
        score = round(score * _ELITE_PROTECT_MULTIPLIER, 5)

    return score


def _select_upset_indices(
    matchups:   list[tuple[dict, dict]],
    win_rates:  dict,
    mode:       str = "balanced",
    round_name: str = "",
    regions:    list[str] | None = None,
) -> dict[int, float]:
    """
    Select upset picks using per-round gates, seed-range rules, and hard caps.

    Eligibility gates (all must pass)
    ----------------------------------
    1. Underdog seed in ROUND_SEED_RANGE[round_name].
       Early rounds (R64–S16): 10–13 only; seeds 8/9 excluded, 14–16 too rare.
       Late rounds (E8+): 2–13, allowing 2/3/4-seeds to beat 1-seeds.
    2. Historical win probability ≥ UPSET_MIN_WIN_PROB[mode] + ROUND_PROB_DELTA[round].
       Later rounds apply a small relaxation (–0.03 to –0.05) to admit the
       historically common 2v1 and 3v1 matchups without requiring a threshold change.
    3. Composite desirability ≥ UPSET_MIN_DESIRABILITY[mode].

    Ranking and caps
    ----------------
    • Eligible candidates are ranked by desirability (highest first).
    • UPSET_MAX_BY_ROUND[round_name][mode] caps the total picks.
    • Round of 64 only: per-region caps and mid-tier cluster cap enforce
      UPSET_MAX_PER_REGION_R64 and UPSET_MAX_MID_TIER_PER_REGION.

    Final Four soft balance (Elite 8 only)
    ---------------------------------------
    Before ranking, desirability scores for E8 candidates are scaled by
    _FF_BALANCE_MULTIPLIER[projected_1seeds_in_ff].  This is a soft scoring
    adjustment, not a hard constraint: it shifts which upsets rank highest
    when the cap is binding, nudging toward ~2 1-seeds in the Final Four
    without blocking any specific outcome.

    Returns
    -------
    dict mapping matchup index → upset_quality score.
    Indices absent from the dict are resolved as favorite wins.
    """
    base_min_prob = UPSET_MIN_WIN_PROB.get(mode, 0.22)
    min_desir     = UPSET_MIN_DESIRABILITY.get(mode, 0.09)
    prob_delta    = ROUND_PROB_DELTA.get(round_name, 0.0)
    effective_min_prob = max(0.0, base_min_prob + prob_delta)
    seed_min, seed_max = ROUND_SEED_RANGE.get(round_name, (10, 13))

    # ── Build eligible candidates ──────────────────────────────────────────
    candidates: list[tuple[int, float, dict, dict, str]] = []

    for i, (team_a, team_b) in enumerate(matchups):
        # 8/9 games: never count as upsets
        if _is_8v9(team_a["seed"], team_b["seed"]):
            continue

        # Identify favorite and underdog by seed number
        if team_a["seed"] < team_b["seed"]:
            fav, und = team_a, team_b
        elif team_b["seed"] < team_a["seed"]:
            fav, und = team_b, team_a
        else:
            continue   # same seed — no upset possible

        # Value-based advancement (Sweet 16 + Elite 8):
        # Pre-compute BEFORE the seed-range gate so the bypass can override it.
        # Conditions: model value_score > 0.10  AND  model win_prob > 0.35.
        # This allows 3/4/5-seeds with high leverage to advance even when they
        # fall outside the normal seed range or desirability thresholds.
        value_bypass = False
        if round_name in ("Sweet 16", "Elite 8") and _HAS_TEAM_RATINGS:
            if "team_rating" in und and "team_rating" in fav:
                _wp_m = _predict_win_probability(und, fav)["team_a"]
                _vs   = _wp_m - _get_public_pick_pct(und, fav)
                if _vs > 0.10 and _wp_m > 0.35:
                    value_bypass = True

        # Gate 0: underdog seed in allowed range for this round.
        # Value bypass overrides the seed-range restriction in S16 and E8,
        # allowing 3–9 seeds with high value to be considered for upsets.
        if not (seed_min <= und["seed"] <= seed_max):
            if not value_bypass:
                continue

        # Gate 1: historical win probability (with round-specific relaxation).
        # Value bypass also overrides this gate — model wp already accounts for
        # team quality; the seed-only historical rate can be too conservative.
        win_prob = _upset_rate(fav["seed"], und["seed"], win_rates)
        if win_prob < effective_min_prob:
            if not value_bypass:
                continue

        # Gate 2: composite desirability
        desir = _upset_desirability(team_a, team_b, win_rates, round_name)
        if desir < min_desir:
            if not value_bypass:
                continue
            desir = min_desir   # floor to minimum so it enters candidates

        region = regions[i] if regions else ""
        candidates.append((i, desir, fav, und, region, value_bypass))

    # ── E8 Final Four soft balance adjustment ─────────────────────────────
    # Count how many E8 games have a 1-seed as the lower-seed (default winner).
    # Apply a desirability multiplier that steers toward ~2 1-seeds in the FF.
    if round_name == "Elite 8" and candidates:
        projected_1seeds = sum(
            1 for a, b in matchups
            if min(a["seed"], b["seed"]) == 1
        )
        ff_bias = _FF_BALANCE_MULTIPLIER.get(projected_1seeds, 1.0)
        candidates = [(i, d * ff_bias, fav, und, r, vb)
                      for i, d, fav, und, r, vb in candidates]

    # ── Rank by (adjusted) desirability descending ────────────────────────
    candidates.sort(key=lambda x: -x[1])

    # ── Greedily select within caps ───────────────────────────────────────
    total_cap = UPSET_MAX_BY_ROUND.get(round_name, {}).get(mode, len(candidates))

    selected:        dict[int, float] = {}
    region_count:    dict[str, int]   = {}
    region_midtier:  dict[str, int]   = {}
    seed_line_count: dict[int, int]   = {}   # R64 only: global per-seed-line tally

    r64_seed_caps = R64_GLOBAL_SEED_CAPS.get(mode, {}) if round_name == "Round of 64" else {}

    for i, desir, fav, und, region, value_bypass in candidates:
        if len(selected) >= total_cap:
            break

        # Soft gate: second E8 upset in balanced mode requires higher quality.
        # value_bypass overrides this gate — a high-value underdog may advance
        # even if their desirability score is below the second-upset threshold.
        if (round_name == "Elite 8" and mode == "balanced"
                and len(selected) >= 1
                and desir < _BALANCED_E8_SECOND_GATE
                and not value_bypass):
            continue

        if round_name == "Round of 64":
            # Global seed-line cap: at most N winners per underdog seed number.
            # Picks the strongest N candidates across the whole field for each
            # seed line, preventing one line (e.g. all four 10-seeds) from
            # monopolising the upsets while no 12-seeds advance.
            und_seed = und["seed"]
            if und_seed in r64_seed_caps:
                if seed_line_count.get(und_seed, 0) >= r64_seed_caps[und_seed]:
                    continue
                seed_line_count[und_seed] = seed_line_count.get(und_seed, 0) + 1

            # Per-region caps: at most 2 upsets per region total, at most 2
            # from the 10/11/12 mid-tier cluster.
            if region_count.get(region, 0) >= UPSET_MAX_PER_REGION_R64:
                # Undo the seed-line increment since we're skipping this pick.
                if und_seed in r64_seed_caps:
                    seed_line_count[und_seed] -= 1
                continue
            if (fav["seed"], und["seed"]) in _MID_TIER_MATCHUPS:
                if region_midtier.get(region, 0) >= UPSET_MAX_MID_TIER_PER_REGION:
                    if und_seed in r64_seed_caps:
                        seed_line_count[und_seed] -= 1
                    continue
                region_midtier[region] = region_midtier.get(region, 0) + 1
            region_count[region] = region_count.get(region, 0) + 1

        selected[i] = round(desir, 5)

    return selected


# Sweet 16 DD target ranges per mode
_S16_DD_TARGETS: dict[str, tuple[int, int]] = {
    "conservative": (0, 1),
    "balanced":     (1, 1),
    "upset_heavy":  (1, 2),
}


def _enforce_s16_dd_constraint(
    matchups:   list[tuple[dict, dict]],
    upset_map:  dict[int, float],
    mode:       str,
    win_rates:  dict,
) -> tuple[dict[int, float], list[str]]:
    """
    Post-process the R32 upset selection so the number of double-digit seeds
    (seed ≥ 10) that advance to the Sweet 16 satisfies the mode's target range.

    Rules
    -----
    conservative : 0 – 1  (trim excess; don't force one in)
    balanced     : exactly 1  (trim excess OR force one in)
    upset_heavy  : 1 – 2  (force one in if 0; trim if >2)

    Strategy
    --------
    • Too many DD winners → remove the lowest-scoring DD winner(s) by
      flipping their game back to the single-digit team.
    • Too few DD winners  → promote the most plausible DD loser (ranked by
      upset desirability then team score) by flipping their game.

    Flipping a game means toggling its index in the upset set so the desired
    team wins.  The upset-count for R32 may shift by ±1 per forced flip —
    structural compliance takes priority over the upset-count target when
    the two conflict.

    Returns
    -------
    adjusted_indices : updated upset set
    notes            : human-readable strings describing each forced change
    """
    notes: list[str] = []

    if mode not in _S16_DD_TARGETS:
        return upset_map, notes

    target_min, target_max = _S16_DD_TARGETS[mode]
    adjusted: dict[int, float] = dict(upset_map)   # index → quality score

    def _sim_winner_loser(i: int) -> tuple[dict, dict]:
        """Simulate game i and return (winner, loser) given current adjusted."""
        team_a, team_b = matchups[i]
        if _is_8v9(team_a["seed"], team_b["seed"]):
            if team_a["score"] >= team_b["score"]:
                return team_a, team_b
            return team_b, team_a
        fav, und = (
            (team_a, team_b) if team_a["seed"] < team_b["seed"]
            else (team_b, team_a)
        )
        return (und, fav) if i in adjusted else (fav, und)

    def _flip_to_win(dd_team: dict, i: int, quality: float) -> None:
        """Toggle i so dd_team wins, recording quality score."""
        team_a, team_b = matchups[i]
        fav = team_a if team_a["seed"] < team_b["seed"] else team_b
        if dd_team["seed"] == fav["seed"]:
            adjusted.pop(i, None)       # dd is fav → normal win (not an upset)
        else:
            adjusted[i] = quality       # dd is und → upset win

    def _flip_to_lose(dd_team: dict, i: int) -> None:
        """Toggle i so dd_team loses."""
        team_a, team_b = matchups[i]
        fav = team_a if team_a["seed"] < team_b["seed"] else team_b
        if dd_team["seed"] == fav["seed"]:
            # dd was winning as favorite; make them lose = now an upset
            q = _upset_desirability(team_a, team_b, win_rates)
            adjusted[i] = q
        else:
            # dd was winning as underdog; remove the upset → favorite wins
            adjusted.pop(i, None)

    # ── Iteratively fix excess DD winners ────────────────────────────────────
    for _ in range(16):
        sim = [_sim_winner_loser(i) for i in range(len(matchups))]
        dd_winners = [(i, w, l) for i, (w, l) in enumerate(sim) if w["seed"] >= 10]
        if len(dd_winners) <= target_max:
            break
        worst_i, worst_dd, replacement = min(dd_winners, key=lambda x: x[1]["score"])
        _flip_to_lose(worst_dd, worst_i)
        notes.append(
            f"S16 constraint ({mode}): removed {worst_dd['name']} "
            f"(seed {worst_dd['seed']}), advanced "
            f"{replacement['name']} (seed {replacement['seed']}) instead"
        )

    # ── Iteratively force DD winners if too few ───────────────────────────────
    for _ in range(16):
        sim = [_sim_winner_loser(i) for i in range(len(matchups))]
        dd_count = sum(1 for w, _ in sim if w["seed"] >= 10)
        if dd_count >= target_min:
            break
        dd_losers = []
        for i, (w, l) in enumerate(sim):
            if l["seed"] < 10:
                continue
            if _is_8v9(matchups[i][0]["seed"], matchups[i][1]["seed"]):
                continue
            d = _upset_desirability(matchups[i][0], matchups[i][1], win_rates)
            dd_losers.append((i, l, w, d))
        if not dd_losers:
            break
        best_i, best_dd, displaced, best_d = max(
            dd_losers, key=lambda x: (x[3], x[1]["score"])
        )
        _flip_to_win(best_dd, best_i, round(best_d, 5))
        notes.append(
            f"S16 constraint ({mode}): forced {best_dd['name']} "
            f"(seed {best_dd['seed']}) to Sweet 16 — displaced "
            f"{displaced['name']} (seed {displaced['seed']})"
        )

    return adjusted, notes


# ════════════════════════════════════════════════════════════════════════════
# Round simulation
# ════════════════════════════════════════════════════════════════════════════



def _play_game(
    team_a:        dict,
    team_b:        dict,
    is_upset_pick: bool,
    round_name:    str,
    region:        str,
    upset_quality: float | None = None,
) -> dict:
    """
    Resolve a single game and return a structured result dict.

    For 8v9: winner is always the higher-rated team; is_upset is forced False.
    For all others: is_upset_pick drives whether the underdog or favorite wins.

    upset_quality, when provided, is attached to the result so the bracket
    output carries a visible ranking of how plausible each upset pick was.
    """
    if _is_8v9(team_a["seed"], team_b["seed"]):
        winner = team_a if team_a["score"] >= team_b["score"] else team_b
        loser  = team_b if winner is team_a else team_a
        is_upset = False
    else:
        if team_a["seed"] < team_b["seed"]:
            fav, und = team_a, team_b
        else:
            fav, und = team_b, team_a

        if is_upset_pick:
            winner, loser, is_upset = und, fav, True
        else:
            winner, loser, is_upset = fav, und, False

    result = {
        "winner":   winner,
        "loser":    loser,
        "is_upset": is_upset,
        "round":    round_name,
        "region":   region,
    }
    if is_upset and upset_quality is not None:
        result["upset_quality"] = upset_quality
    return result


def _simulate_round(
    matchups:      list[tuple[dict, dict, str]],   # (team_a, team_b, region)
    upset_map:     dict[int, float],               # index → upset_quality score
    round_name:    str,
) -> tuple[list[dict], list[dict]]:
    """
    Simulate all games in one round.

    upset_map maps matchup index to upset_quality score for every game
    that should be played as an upset.  Indices absent from the map are
    resolved as favorite wins.

    Returns
    -------
    results  : list of game-result dicts (for bracket output)
    winners  : list of winning team dicts, in matchup order
    """
    results: list[dict] = []
    winners: list[dict] = []

    for i, (team_a, team_b, region) in enumerate(matchups):
        quality = upset_map.get(i)
        result  = _play_game(
            team_a, team_b,
            is_upset_pick=(i in upset_map),
            round_name=round_name,
            region=region,
            upset_quality=quality,
        )
        results.append(result)
        winners.append(result["winner"])

    return results, winners


# ── Seed shrinkage for champion selection ─────────────────────────────────────
# Historical per-seed championship rate (fraction of total titles, ~35 years).
# 1-seeds win ~63% of all championships; 2-seeds only ~11%.
# Used to shrink the model's over-confidence in 2-seeds at the final pick.
# To revert: remove HISTORICAL_CHAMP_RATE, _adjust_champion_probability, and
# the two adjusted-prob lines in _apply_champion_filter.
HISTORICAL_CHAMP_RATE: dict[int, float] = {
    1: 0.63,
    2: 0.11,
    3: 0.09,
    4: 0.03,
    5: 0.03,
    6: 0.02,
    7: 0.01,
    8: 0.01,
}

def _adjust_champion_probability(model_prob: float, seed: int, blend: float = 0.25) -> float:
    """
    Blend model win probability with historical seed championship rate.
    adjusted = (1 - blend) * model_prob + blend * hist_rate
    Reduces over-selection of 2-seeds whose model_prob exceeds their historical base.
    """
    hist = HISTORICAL_CHAMP_RATE.get(int(seed), 0.005)
    return (1.0 - blend) * model_prob + blend * hist


def _apply_champion_filter(
    team_a:            dict,
    team_b:            dict,
    champ_sel:         dict[int, float],
    candidates:        frozenset[str],
    strict_candidates: frozenset[str],
) -> dict[int, float]:
    """
    Override championship game selection using strict filter first, then broad pool.

    Strict pool active (non-empty):
      score = 0.50 × win_probability + 0.50 × champion_profile_score
    Fallback (strict empty → broad candidates):
      score = 0.75 × win_probability + 0.25 × champion_profile_score

    Cases:
      • Both finalists in active pool → pick by score formula.
      • Exactly one in active pool    → that team wins.
      • Neither in active pool        → pick by score formula (best available).
    """
    use_strict = bool(strict_candidates)
    active     = strict_candidates if use_strict else candidates
    wp_weight  = 0.50 if use_strict else 0.75
    cps_weight = 0.50 if use_strict else 0.25

    a_in = team_a["name"] in active
    b_in = team_b["name"] in active

    if a_in and b_in:
        wp    = _predict_win_probability(team_a, team_b)
        wp_a  = float(wp["team_a"])
        wp_b  = float(wp["team_b"])
        # Seed shrinkage: blend model wp with historical seed championship rate.
        # Raw wp is preserved; only the score formula uses adjusted values.
        adj_wp_a = _adjust_champion_probability(wp_a, team_a.get("seed", 8))
        adj_wp_b = _adjust_champion_probability(wp_b, team_b.get("seed", 8))
        cps_a = float(team_a.get("champion_profile_score", team_a.get("profile_score", 0.5)))
        cps_b = float(team_b.get("champion_profile_score", team_b.get("profile_score", 0.5)))
        score_a = wp_weight * adj_wp_a + cps_weight * cps_a
        score_b = wp_weight * adj_wp_b + cps_weight * cps_b
        winner_should_be_a = score_a >= score_b
    elif not a_in and not b_in:
        # Neither qualifies — formula as fallback
        wp    = _predict_win_probability(team_a, team_b)
        wp_a  = float(wp["team_a"])
        wp_b  = float(wp["team_b"])
        # Seed shrinkage applied here too for consistency.
        adj_wp_a = _adjust_champion_probability(wp_a, team_a.get("seed", 8))
        adj_wp_b = _adjust_champion_probability(wp_b, team_b.get("seed", 8))
        cps_a = float(team_a.get("champion_profile_score", team_a.get("profile_score", 0.5)))
        cps_b = float(team_b.get("champion_profile_score", team_b.get("profile_score", 0.5)))
        score_a = wp_weight * adj_wp_a + cps_weight * cps_a
        score_b = wp_weight * adj_wp_b + cps_weight * cps_b
        winner_should_be_a = score_a >= score_b
    else:
        # Exactly one qualifies — that team wins
        winner_should_be_a = a_in

    # Determine what the current champ_sel would produce.
    is_upset = (0 in champ_sel)
    if team_a["seed"] <= team_b["seed"]:
        current_winner_is_a = not is_upset
    else:
        current_winner_is_a = is_upset

    if current_winner_is_a == winner_should_be_a:
        return champ_sel   # already produces the right winner

    # Need to flip: toggle upset flag
    if is_upset:
        return {}          # remove upset → favorite wins
    else:
        return {0: 1.0}    # add upset → underdog wins


# ════════════════════════════════════════════════════════════════════════════
# Full bracket simulation
# ════════════════════════════════════════════════════════════════════════════

def simulate_bracket(
    mode: str = "balanced",
    *,
    season:              int | None = None,
    _teams_override:     dict | None = None,
    _probs_override:     dict | None = None,
    _structure_override: dict | None = None,
) -> dict:
    """
    Simulate a complete NCAA tournament bracket.

    Parameters
    ----------
    mode : "conservative" | "balanced" | "upset_heavy"
           Must match a key in optimal_bracket_structure.json.

    Returns
    -------
    {
      "mode":          str,
      "round_of_64":   [game_result, ...],   # 32 games
      "round_of_32":   [game_result, ...],   # 16 games
      "sweet_16":      [game_result, ...],   # 8 games
      "elite_8":       [game_result, ...],   # 4 games
      "final_four":    [game_result, ...],   # 2 games
      "championship":  game_result,          # 1 game
      "champion":      team_dict,
      "reasoning":     {...},
      "structure_check": {...},
    }
    """
    # ── Load inputs ───────────────────────────────────────────────────────
    # Each input can be overridden (used by the backtest engine to inject
    # pre-tournament-only data without writing to disk).
    if _structure_override is not None:
        opt = _structure_override
    else:
        with open(OPT_FILE) as f: opt = json.load(f)

    if _probs_override is not None:
        probs = _probs_override
    else:
        with open(PROBS_FILE) as f: probs = json.load(f)

    structure     = opt[mode]
    upset_profile = structure["upset_profile"]
    win_rates     = probs["matchup_win_rates"]
    adv_rates     = probs["advancement_rates"]

    # ── Build scored team dicts ───────────────────────────────────────────
    # teams[region][seed] = full team dict including computed score
    teams_source = _teams_override if _teams_override is not None else MOCK_TEAMS
    teams: dict[str, dict[int, dict]] = {}
    for region, seed_map in teams_source.items():
        teams[region] = {}
        for seed, info in seed_map.items():
            t = {**info, "seed": seed, "region": region}
            t["score"] = score_team(t, adv_rates)
            teams[region][seed] = t

    # ── Attach team ratings when available ────────────────────────────────
    # Strategy:
    #   1. Try historical_team_ratings.csv (covers backtest years 1990–2016,
    #      uses "T{id}" team names keyed by integer team_id).
    #   2. Fall back to team_ratings.csv (covers current/sample seasons with
    #      real or fictional team names).
    # Within each source, matching order per team:
    #   a. team_id match  — extract id from "T{id}" name, look up by integer
    #   b. name match     — direct string lookup in team_name column
    #   c. seed fallback  — no rating attached; seed-based logic used
    _ratings_diagnostics: dict = {
        "season":          season,
        "source":          None,
        "matched_by_id":   0,
        "matched_by_name": 0,
        "seed_fallback":   0,
        "total_teams":     sum(len(seeds_map) for seeds_map in teams.values()),
    }
    # Raw offense/KT values for strict champion filter — keyed by team name.
    # Stored separately so they don't alter the team dict fields that feed
    # _offense_rank (used by the broad candidate pool).
    _strict_team_stats: dict[str, dict] = {}

    if _HAS_TEAM_RATINGS and season is not None:
        _ratings_df = None
        try:
            # Prefer historical ratings for seasons with pre-computed history
            hist_df = _load_historical_ratings()
            if hist_df is not None and season in hist_df["season"].values:
                _ratings_df = hist_df
                _ratings_diagnostics["source"] = "historical_team_ratings.csv"
            else:
                # Fall back to current-season ratings file
                curr_df = _load_team_ratings()
                if season in curr_df["season"].values:
                    _ratings_df = curr_df
                    _ratings_diagnostics["source"] = "team_ratings.csv"
        except Exception:
            _ratings_df = None

        if _ratings_df is not None:
            for region in teams:
                for seed_num in teams[region]:
                    t    = teams[region][seed_num]
                    name = t["name"]
                    rec  = None

                    # (a) team_id match
                    m = _TEAM_ID_RE.match(name)
                    if m:
                        tid = int(m.group(1))
                        rec = _get_team_rating_by_id(_ratings_df, tid, season)
                        if rec:
                            _ratings_diagnostics["matched_by_id"] += 1

                    # (b) name match
                    if rec is None:
                        rec = _get_team_rating(_ratings_df, name, season)
                        if rec:
                            _ratings_diagnostics["matched_by_name"] += 1

                    # (c) seed fallback — nothing to do
                    if rec is None:
                        _ratings_diagnostics["seed_fallback"] += 1
                        continue

                    t["team_rating"]            = float(rec["team_rating"])
                    t["champion_profile_score"] = float(rec["champion_profile_score"])
                    if "profile_score" in rec and rec["profile_score"] is not None:
                        t["profile_score"] = float(rec["profile_score"])
                    try:
                        ap_flag = rec.get("ap_top12_flag")
                        if ap_flag is not None and ap_flag == ap_flag:  # NaN-safe
                            t["ap_top12_flag"] = int(ap_flag)
                    except (TypeError, ValueError):
                        pass
                    # Store offense/KT separately for strict champion filter.
                    # NOT on team dict so _offense_rank (broad pool) stays unchanged.
                    _st: dict = {}
                    for _fld in ("offense_rating", "kenpom_torvik_rating"):
                        _val = rec.get(_fld)
                        if _val is not None and _val == _val:  # NaN-safe
                            try:
                                _st[_fld] = float(_val)
                            except (TypeError, ValueError):
                                pass
                    if _st:
                        _strict_team_stats[name] = _st
                    t["score"] = score_team(t, adv_rates)
        else:
            _ratings_diagnostics["seed_fallback"] = _ratings_diagnostics["total_teams"]

    # ── Champion candidate pool ───────────────────────────────────────────
    # Seed-based constraint layer:
    #   Primary: seed <= 2
    #   Seed 3 allowed if: top-10 in team_rating AND top-15 in offensive efficiency
    # If fewer than 2 teams survive, relax to the top-4 by team_rating.
    all_teams_flat = [
        t for region in teams.values() for t in region.values()
    ]

    # Compute within-field ranks for seed-3 exception check, elite bonus,
    # and contender bonus.
    _sorted_by_rating = sorted(
        all_teams_flat, key=lambda t: float(t.get("team_rating", 0.0)), reverse=True
    )
    _sorted_by_offense = sorted(
        all_teams_flat, key=lambda t: float(t.get("offense_rating", 0.0)), reverse=True
    )
    _sorted_by_cps = sorted(
        all_teams_flat,
        key=lambda t: float(t.get("champion_profile_score", t.get("profile_score", 0.0))),
        reverse=True,
    )
    _rating_rank  = {t["name"]: i + 1 for i, t in enumerate(_sorted_by_rating)}
    _offense_rank = {t["name"]: i + 1 for i, t in enumerate(_sorted_by_offense)}
    _cps_rank     = {t["name"]: i + 1 for i, t in enumerate(_sorted_by_cps)}

    # Strict-filter rank dicts — built from separately stored real-data stats,
    # independent of _offense_rank so the broad candidate pool is unaffected.
    _strict_offense_rank = {
        t["name"]: i + 1
        for i, t in enumerate(
            sorted(all_teams_flat,
                   key=lambda t: _strict_team_stats.get(t["name"], {}).get("offense_rating", 0.0),
                   reverse=True)
        )
    }
    _strict_kt_rank = {
        t["name"]: i + 1
        for i, t in enumerate(
            sorted(all_teams_flat,
                   key=lambda t: _strict_team_stats.get(t["name"], {}).get("kenpom_torvik_rating", 0.0),
                   reverse=True)
        )
    }
    def _is_champion_candidate(t: dict) -> bool:
        seed = t["seed"]
        if seed <= 2:
            return True
        if seed == 3:
            return (
                _rating_rank.get(t["name"], 999) <= 10
                and _offense_rank.get(t["name"], 999) <= 15
            )
        return False

    qualified = [t for t in all_teams_flat if _is_champion_candidate(t)]
    if len(qualified) < 2:
        # Relax: top-4 by team_rating
        qualified = _sorted_by_rating[:4]
    _champion_candidate_names: frozenset[str] = frozenset(t["name"] for t in qualified)

    # ── Strict champion filter helpers ────────────────────────────────────
    # Used only at the final championship selection; not applied to earlier rounds.
    # AP rule is only enforced when real AP data is present in the field.
    # KT rule requires real kenpom_torvik_rating data; without it the strict
    # filter is skipped entirely (falls back to broad candidate pool).
    _ap_data_available: bool = any(t.get("ap_top12_flag", 0) == 1 for t in all_teams_flat)
    _kt_data_available: bool = any(
        "kenpom_torvik_rating" in _strict_team_stats.get(t["name"], {})
        for t in all_teams_flat
    )

    def _strict_finalist_check(
        t:              dict,
        offense_top:    int  = 10,
        kt_top:         int  = 10,
        any_top8_2seed: bool = False,
    ) -> bool:
        nm     = t["name"]
        seed   = t["seed"]
        ap_ok  = (not _ap_data_available) or (t.get("ap_top12_flag", 0) == 1)
        off_ok = _strict_offense_rank.get(nm, 999) <= offense_top
        kt_ok  = _strict_kt_rank.get(nm, 999) <= kt_top

        if seed == 1:
            return ap_ok and off_ok and kt_ok
        if seed == 2:
            if any_top8_2seed:
                return _rating_rank.get(nm, 999) <= 8
            # Exceptional 2-seed: top-5 rating + top-5 CPS + 3 of 4 profile rules
            if _rating_rank.get(nm, 999) > 5 or _cps_rank.get(nm, 999) > 5:
                return False
            return sum([ap_ok, off_ok, kt_ok]) >= 3  # seed rule counts as not met → max 3
        return False

    def _build_strict_champ_pool(finalist_a: dict, finalist_b: dict) -> frozenset[str]:
        """
        Try strict → progressively relaxed criteria against the two finalists.
        Returns the qualifying subset, or empty frozenset to trigger fallback.
        Immediately returns empty when KT data is unavailable (proxy-only years).
        """
        if not _kt_data_available:
            return frozenset()
        finalists = [finalist_a, finalist_b]
        for offense_top, kt_top, any_top8 in [
            (10, 10, False),   # Tier 1: strict
            (15, 10, False),   # Tier 2: relax offense to top-15
            (15, 12, False),   # Tier 3: relax KenPom/Torvik to top-12
            (15, 12, True),    # Tier 4: allow any 2-seed with top-8 team_rating
        ]:
            pool = frozenset(
                t["name"] for t in finalists
                if _strict_finalist_check(t, offense_top, kt_top, any_top8)
            )
            if pool:
                return pool
        return frozenset()  # no qualifier → caller falls back to broad pool

    bracket: dict = {
        "mode": mode,
        "round_of_64":  [],
        "round_of_32":  [],
        "sweet_16":     [],
        "elite_8":      [],
        "final_four":   [],
        "championship": None,
        "champion":     None,
    }

    # ── Round of 64 (32 games) ────────────────────────────────────────────
    # Build matchup list preserving region and slot index for later pairing
    r64_matchups: list[tuple[dict, dict, str]] = []
    for region in REGIONS:
        for lo_seed, hi_seed in R64_MATCHUPS:
            r64_matchups.append((teams[region][lo_seed],
                                 teams[region][hi_seed],
                                 region))

    r64_sel = _select_upset_indices(
        [(a, b) for a, b, _ in r64_matchups],
        win_rates=win_rates,
        mode=mode,
        round_name="Round of 64",
        regions=[r for _, _, r in r64_matchups],
    )
    r64_results, r64_winners = _simulate_round(r64_matchups, r64_sel, "Round of 64")
    bracket["round_of_64"] = r64_results

    # Organise R64 winners by region × slot for R32 pairing
    # r64_winners order: 8 per region × 4 regions = 32 entries
    r64_by_region: dict[str, list[dict]] = {r: [] for r in REGIONS}
    for idx, w in enumerate(r64_winners):
        r64_by_region[REGIONS[idx // 8]].append(w)

    # ── Round of 32 (16 games) ────────────────────────────────────────────
    r32_matchups: list[tuple[dict, dict, str]] = []
    for region in REGIONS:
        slots = r64_by_region[region]   # 8 winners, in R64 slot order
        for g1, g2 in R32_PAIRS:
            team_a, team_b = slots[g1], slots[g2]
            r32_matchups.append((team_a, team_b, region))

    r32_sel = _select_upset_indices(
        [(a, b) for a, b, _ in r32_matchups],
        win_rates=win_rates,
        mode=mode,
        round_name="Round of 32",
        regions=[r for _, _, r in r32_matchups],
    )
    r32_sel, s16_notes = _enforce_s16_dd_constraint(
        [(a, b) for a, b, _ in r32_matchups],
        r32_sel,
        mode,
        win_rates,
    )
    r32_results, r32_winners = _simulate_round(r32_matchups, r32_sel, "Round of 32")
    bracket["round_of_32"]       = r32_results
    bracket["s16_constraint_notes"] = s16_notes

    r32_by_region: dict[str, list[dict]] = {r: [] for r in REGIONS}
    for idx, w in enumerate(r32_winners):
        r32_by_region[REGIONS[idx // 4]].append(w)

    # ── Sweet 16 (8 games) ────────────────────────────────────────────────
    s16_matchups: list[tuple[dict, dict, str]] = []
    for region in REGIONS:
        slots = r32_by_region[region]   # 4 winners
        for g1, g2 in S16_PAIRS:
            s16_matchups.append((slots[g1], slots[g2], region))

    s16_sel = _select_upset_indices(
        [(a, b) for a, b, _ in s16_matchups],
        win_rates=win_rates,
        mode=mode,
        round_name="Sweet 16",
        regions=[r for _, _, r in s16_matchups],
    )
    s16_results, s16_winners = _simulate_round(s16_matchups, s16_sel, "Sweet 16")
    bracket["sweet_16"] = s16_results

    s16_by_region: dict[str, list[dict]] = {r: [] for r in REGIONS}
    for idx, w in enumerate(s16_winners):
        s16_by_region[REGIONS[idx // 2]].append(w)

    # ── Elite 8 (4 games, one per region) ────────────────────────────────
    e8_matchups: list[tuple[dict, dict, str]] = []
    for region in REGIONS:
        a, b = s16_by_region[region]
        e8_matchups.append((a, b, region))

    e8_sel = _select_upset_indices(
        [(a, b) for a, b, _ in e8_matchups],
        win_rates=win_rates,
        mode=mode,
        round_name="Elite 8",
        regions=[r for _, _, r in e8_matchups],
    )
    e8_results, e8_winners = _simulate_round(e8_matchups, e8_sel, "Elite 8")
    bracket["elite_8"] = e8_results
    # e8_winners[i] is the champion of REGIONS[i]

    # ── Final Four (2 games) ─────────────────────────────────────────────
    # East vs West, South vs Midwest
    ff_matchups: list[tuple[dict, dict, str]] = []
    for ri, rj in FF_REGION_PAIRS:
        ff_matchups.append((e8_winners[ri], e8_winners[rj], "National"))

    ff_sel = _select_upset_indices(
        [(a, b) for a, b, _ in ff_matchups],
        win_rates=win_rates,
        mode=mode,
        round_name="Final Four",
        regions=[r for _, _, r in ff_matchups],
    )
    ff_results, ff_winners = _simulate_round(ff_matchups, ff_sel, "Final Four")
    bracket["final_four"] = ff_results

    # ── Championship (1 game) ─────────────────────────────────────────────
    champ_matchups = [(ff_winners[0], ff_winners[1], "National")]
    champ_sel = _select_upset_indices(
        [(a, b) for a, b, _ in champ_matchups],
        win_rates=win_rates,
        mode=mode,
        round_name="Championship",
        regions=[r for _, _, r in champ_matchups],
    )
    # Apply strict champion filter (falls back to broad pool if no strict qualifier).
    _strict_champ_pool = _build_strict_champ_pool(ff_winners[0], ff_winners[1])
    champ_sel = _apply_champion_filter(
        ff_winners[0], ff_winners[1], champ_sel,
        _champion_candidate_names, _strict_champ_pool,
    )
    champ_results, champ_winners = _simulate_round(champ_matchups, champ_sel, "Championship")
    bracket["championship"] = champ_results[0]
    bracket["champion"]     = champ_winners[0]

    # ── Value diagnostics ─────────────────────────────────────────────────
    # Compute and store value_score for the champion and both finalists so
    # backtest reporting can track ownership/leverage performance.
    _champ  = bracket["champion"]
    _runner = bracket["championship"]["loser"]
    if "team_rating" in _champ and "team_rating" in _runner:
        _champ_wp  = _predict_win_probability(_champ, _runner)["team_a"]
        _champ_pub = _get_public_pick_pct(_champ, _runner)
        bracket["champion_value_score"] = round(_champ_wp - _champ_pub, 4)
        bracket["champion_win_prob"]    = round(_champ_wp, 4)
        bracket["champion_public_pct"]  = round(_champ_pub, 4)
    else:
        bracket["champion_value_score"] = None
        bracket["champion_win_prob"]    = None
        bracket["champion_public_pct"]  = None

    # ── Reasoning ────────────────────────────────────────────────────────
    bracket["reasoning"] = _build_reasoning(bracket)

    # ── Structure compliance ──────────────────────────────────────────────
    bracket["structure_check"] = check_structure_compliance(bracket, structure, mode)

    # ── Ratings diagnostics ───────────────────────────────────────────────
    bracket["ratings_diagnostics"] = _ratings_diagnostics

    return bracket


# ════════════════════════════════════════════════════════════════════════════
# Reasoning + compliance
# ════════════════════════════════════════════════════════════════════════════

def _build_reasoning(bracket: dict) -> dict:
    """Construct human-readable notes about the bracket."""
    champ    = bracket["champion"]
    runner   = bracket["championship"]["loser"]

    all_games = (
        bracket["round_of_64"] + bracket["round_of_32"] +
        bracket["sweet_16"]    + bracket["elite_8"]     +
        bracket["final_four"]  + [bracket["championship"]]
    )
    upsets = [g for g in all_games if g["is_upset"]]
    notable = [
        f"{g['winner']['name']} (seed {g['winner']['seed']}) over "
        f"{g['loser']['name']} (seed {g['loser']['seed']}) — {g['round']}"
        for g in upsets
        if g["winner"]["seed"] >= 10   # double-digit seed wins only
    ]

    champion_note = (
        f"{champ['name']} (seed {champ['seed']}, rating {champ['rating']}) "
        f"won the championship over "
        f"{runner['name']} (seed {runner['seed']}, rating {runner['rating']}). "
        f"Score differential: {round(champ['score'] - runner['score'], 4):+.4f}. "
        f"Bracket total upsets: {len(upsets)}."
    )
    if champ["seed"] > 2:
        champion_note += (
            f" Cinderella: a seed-{champ['seed']} champion is historically rare."
        )

    return {
        "champion":         champion_note,
        "total_upsets":     len(upsets),
        "notable_upsets":   notable if notable else ["No double-digit seed upsets."],
    }


def check_structure_compliance(
    bracket:   dict,
    structure: dict,
    mode:      str,
) -> dict:
    """
    Compare the generated bracket's seed distribution against the
    optimizer's target structure and upset targets.

    Upset counts are reported as informational only — no pass/fail gate.
    The only enforced structural constraint is Sweet 16 double-digit seed
    composition.  fully_compliant reflects the DD check exclusively.
    """
    from collections import Counter

    def _seeds_in_round(games: list[dict]) -> list[int]:
        """All seeds that WON their game in this round."""
        return [g["winner"]["seed"] for g in games]

    def _upset_count(games: list[dict]) -> int:
        return sum(1 for g in games if g["is_upset"])

    rounds_map = {
        "round_of_32":  ("round_of_64",  "Round of 64"),
        "sweet_16":     ("round_of_32",  "Round of 32"),
        "elite_8":      ("sweet_16",     "Sweet 16"),
        "final_four":   ("elite_8",      "Elite 8"),
        "championship": ("final_four",   "Final Four"),
    }

    upset_compliance: dict[str, dict] = {}
    for bracket_key, (_, round_name) in rounds_map.items():
        source_games = bracket.get(bracket_key.replace("round_of_32", "round_of_64")
                                              .replace("sweet_16",    "round_of_32")
                                              .replace("elite_8",     "sweet_16")
                                              .replace("final_four",  "elite_8")
                                              .replace("championship","final_four"),
                                   [])

    # Simpler: recompute directly from bracket keys
    round_game_keys = {
        "Round of 64": "round_of_64",
        "Round of 32": "round_of_32",
        "Sweet 16":    "sweet_16",
        "Elite 8":     "elite_8",
        "Final Four":  "final_four",
        "Championship": "championship",
    }
    upset_compliance = {}
    for rname, bkey in round_game_keys.items():
        games = bracket.get(bkey, [])
        if isinstance(games, dict):   # championship is a single dict
            games = [games]
        target = structure["upset_profile"].get(rname, "N/A")
        actual = _upset_count(games)
        upset_compliance[rname] = {
            "target":        target,
            "actual":        actual,
            "ok":            True,    # informational only — no pass/fail gate
            "informational": True,
        }

    # Seed distribution compliance per round
    seed_compliance: dict[str, dict] = {}
    for struct_key, bracket_source in [
        ("round_of_32",  "round_of_64"),
        ("sweet_16",     "round_of_32"),
        ("elite_8",      "sweet_16"),
        ("final_four",   "elite_8"),
        ("championship", "final_four"),
    ]:
        target_seeds  = structure.get(struct_key, [])
        games         = bracket.get(bracket_source, [])
        actual_seeds  = sorted(_seeds_in_round(games))
        target_sorted = sorted(target_seeds if isinstance(target_seeds, list)
                               else [target_seeds])
        seed_compliance[struct_key] = {
            "target": target_sorted,
            "actual": actual_seeds,
            "ok":     actual_seeds == target_sorted,
        }

    # Double-digit seed check — mode-aware target range
    s16_teams = [g["winner"]["seed"] for g in bracket["round_of_32"]]
    dd_in_s16 = sum(1 for s in s16_teams if s >= 10)
    t_min, t_max = _S16_DD_TARGETS.get(mode, (0, 16))
    dd_ok        = t_min <= dd_in_s16 <= t_max
    dd_target_str = str(t_min) if t_min == t_max else f"{t_min}–{t_max}"

    return {
        "mode":                    mode,
        "double_digit_in_sweet16": {
            "actual":     dd_in_s16,
            "target":     dd_target_str,
            "target_min": t_min,
            "target_max": t_max,
            "ok":         dd_ok,
        },
        "upset_compliance":  upset_compliance,
        "seed_compliance":   seed_compliance,
        "fully_compliant":   dd_ok,   # upset counts are informational only
    }
